export const articles = [
  {
    slug: 'pizza-napolitana-autentica', icon: '🍕', tone: 'gold', tag: 'Tradición', minutes: 4,
    title: '¿Qué hace auténtica a una pizza napolitana?',
    excerpt: 'Masa, tiempo y horno a más de 450 °C. Los secretos que separan una napolitana de verdad de una imitación.',
    body: `<p>En PizzPlass nos lo preguntan mucho: «¿qué diferencia hay entre una pizza normal y una napolitana?». La respuesta cabe en tres palabras: <strong>masa, tiempo y fuego</strong>.</p><h2>La masa: pocos ingredientes, mucha paciencia</h2><p>La verdadera pizza napolitana se hace con harina, agua, sal y levadura. El secreto está en el <strong>tiempo de fermentación</strong>: dejamos reposar la masa para que sea ligera, digerible y desarrolle todo su sabor.</p><h2>El borde: alto, aireado y con «leopardo»</h2><p>El famoso <em>cornicione</em> debe quedar hinchado y lleno de aire, con pequeñas manchas tostadas. Es la firma de un horneado a altísima temperatura.</p><blockquote>Una buena napolitana se dobla, no se parte. El centro es fino y tierno; el borde, alto y esponjoso.</blockquote><h2>El horno: más de 450 °C</h2><p>Nuestro horno portátil alcanza entre <strong>430 y 480 °C</strong> y cuece cada pizza en <strong>60–90 segundos</strong>. Ese golpe de calor crea el contraste entre un interior tierno y un exterior ligeramente crujiente.</p><h2>Los ingredientes: menos es más</h2><p>Tomate San Marzano, mozzarella fior di latte, albahaca fresca y AOVE. Cada ingrediente tiene que saber a lo que es.</p><ul><li><strong>Tomate San Marzano:</strong> dulce y poco ácido.</li><li><strong>Mozzarella fior di latte:</strong> fundente y jugosa.</li><li><strong>Albahaca fresca:</strong> aroma inconfundible.</li><li><strong>AOVE:</strong> un hilo de aceite que lo une todo.</li></ul><h2>Hecha con cariño</h2><p>La autenticidad también está en el gesto: amasar a mano, cuidar el fuego y servir la pizza con una sonrisa.</p>`
  },
  {
    slug: 'pizza-en-tu-boda', icon: '💍', tone: 'red', tag: 'Eventos', minutes: 3,
    title: 'Pizza napolitana en tu boda: la sorpresa perfecta',
    excerpt: 'Por qué un horno portátil puede convertirse en el momento más comentado de vuestro gran día.',
    body: `<p>Las bodas evolucionan y cada vez más parejas buscan un detalle que rompa con lo previsible. Un <strong>horno de pizza napolitana en directo</strong> se convierte en uno de los momentos más comentados.</p><h2>Un momento, no solo comida</h2><p>El calor del horno, la masa preparándose y las pizzas saliendo calientes crean un punto de encuentro donde la gente charla y disfruta.</p><blockquote>Una pizza recién salida del horno, compartida de pie y copa en mano, rompe el hielo entre invitados.</blockquote><h2>¿Cuándo encaja?</h2><ul><li><strong>Aperitivo:</strong> pequeñas porciones para picar.</li><li><strong>Barra libre:</strong> la recena que todos agradecen.</li><li><strong>Boda informal:</strong> una propuesta principal relajada y diferente.</li></ul><h2>Ventajas de PizzPlass</h2><ul><li>Nos adaptamos a exteriores e interiores.</li><li>Gusta a pequeños y mayores.</li><li>Ofrecemos opciones vegetarianas y adaptaciones.</li><li>Montamos, cocinamos y recogemos.</li></ul><h2>Nuestro consejo</h2><p>Elige un rincón visible del recinto. Ver el fuego y el trabajo con la masa multiplica el efecto sorpresa.</p>`
  },
  {
    slug: 'historia-pizzplass', icon: '👨‍🍳', tone: 'green', tag: 'Historia', minutes: 3,
    title: 'Dos hermanos, un horno y mucha ilusión',
    excerpt: 'Cómo Leo y Juan Antonio convirtieron una idea compartida en PizzPlass.',
    body: `<p>Detrás de PizzPlass está la historia de dos hermanos, <strong>Leo y Juan Antonio</strong>, que decidieron convertir una pasión compartida en un proyecto propio.</p><h2>La pizza como punto de encuentro</h2><p>La idea tomó forma entre conversaciones, pruebas y ganas de crear algo cercano, con ingredientes cuidados y una experiencia alrededor de la pizza.</p><blockquote>«Un día nos dimos cuenta de que hablábamos siempre de abrir algo nuestro. Así que lo hicimos.»</blockquote><h2>Del sueño al horno</h2><p>Unieron fuerzas para llevar pizza napolitana de calidad directamente a bodas, comuniones, cumpleaños y eventos.</p><h2>Lo que no cambia</h2><p>Han pasado eventos y kilos de harina, pero mantienen las mismas ganas del primer día.</p><ul><li><strong>Masa artesanal</strong> de fermentación lenta.</li><li><strong>Producto de verdad</strong>, sin atajos.</li><li><strong>Trato cercano</strong>, como en familia.</li></ul><p>Lo mejor de la historia de PizzPlass es que solo acaba de empezar.</p>`
  },
  {
    slug: 'secretos-masa-48-horas', icon: '🌾', tone: 'amber', tag: 'Cocina', minutes: 4,
    title: 'El secreto está en la masa: fermentación de 48 horas',
    excerpt: 'Qué aporta el tiempo a la digestibilidad, la textura y el sabor de nuestra masa.',
    body: `<p>Si tuviéramos que elegir un ingrediente de la pizza napolitana, sería el <strong>tiempo</strong>. Trabajamos con fermentaciones largas, de hasta <strong>48 horas</strong>.</p><h2>¿Qué ocurre durante la fermentación?</h2><p>Las levaduras y enzimas transforman lentamente los azúcares y proteínas.</p><ul><li><strong>Desarrolla el sabor:</strong> aparecen aromas que una masa rápida no consigue.</li><li><strong>Mejora la textura:</strong> crea una miga alveolada y un borde aireado.</li><li><strong>Facilita la digestión:</strong> parte del trabajo ya se ha hecho en la masa.</li></ul><blockquote>Una fermentación larga se nota: la pizza resulta ligera y no pesa.</blockquote><h2>¿Por qué 48 horas?</h2><p>Nos dan el equilibrio entre extensibilidad, para estirarla sin romperla, y fuerza, para soportar el golpe de calor.</p><h2>Del frío al fuego</h2><p>La masa pasa del reposo tranquilo al horno durante apenas 60–90 segundos. Ese contraste es parte de la magia napolitana.</p>`
  },
  {
    slug: 'como-elegir-catering-evento', icon: '✨', tone: 'cream', tag: 'Consejos', minutes: 4,
    title: 'Cómo elegir el catering perfecto para tu evento',
    excerpt: 'Cinco claves para acertar con la comida y dejar un buen recuerdo en tus invitados.',
    body: `<p>La comida es uno de los recuerdos que más perduran de cualquier celebración. Estas son cinco claves aprendidas evento tras evento.</p><h2>1. Piensa en tus invitados</h2><p>Niños, mayores, alergias y preferencias. Un buen catering se adapta a quien va a comer.</p><h2>2. El formato marca el ambiente</h2><ul><li><strong>Formal:</strong> menú servido en mesa.</li><li><strong>Distendido:</strong> estaciones donde la gente socializa.</li><li><strong>Fiesta:</strong> algo rico para mantener la energía.</li></ul><blockquote>La comida no solo alimenta: crea ambiente y conversación.</blockquote><h2>3. Valora la experiencia</h2><p>Ver cómo se prepara la comida en directo convierte el servicio en un recuerdo.</p><h2>4. Pide claridad</h2><p>Pregunta qué incluye el presupuesto: montaje, personal, raciones, adaptaciones y recogida.</p><h2>5. Confía en quien lo hace con pasión</h2><p>Busca proveedores cercanos, que escuchen tu idea y se impliquen de verdad.</p>`
  },
  {
    slug: 'horno-lena-espectaculo', icon: '🔥', tone: 'dark', tag: 'Experiencia', minutes: 3,
    title: 'El horno portátil: mucho más que cocinar',
    excerpt: 'Calor, fuego y elaboración en directo: por qué nuestro horno se convierte en protagonista.',
    body: `<p>Pocas cosas se acercan a la experiencia de un <strong>horno portátil</strong> encendido en mitad de una celebración. Es limpio, seguro y práctico para distintos espacios.</p><h2>El calor que lo cambia todo</h2><p>Alcanza temperaturas altísimas y cocina cada pizza en menos de dos minutos, con un borde alto y aireado.</p><blockquote>La gente se acerca, ve la pizza hincharse en segundos y ahí empieza la magia.</blockquote><h2>La elaboración, protagonista</h2><p>Estirar la masa, montar cada pizza y verla entrar en el horno forma parte de la experiencia. Los invitados se acercan, preguntan y hacen fotos.</p><h2>El sabor napolitano</h2><p>El golpe de calor sella la masa, sube el borde y mantiene la pizza tierna por dentro.</p><h2>Una experiencia completa</h2><p>Aroma, fuego, destreza y sabor. No solo llevamos pizza: llevamos <strong>un momento que los invitados recuerdan</strong>.</p>`
  }
];

export const articleBySlug = Object.fromEntries(articles.map((article) => [article.slug, article]));
